### ISSUE TITLE
Kompatiblität mit Typo3 10

### ISSUE THREAD

**Issue by casimir374** [HamburgerJungeJr/fe_user_cards#1]
[Classes.txt](https://github.com/HamburgerJungeJr/fe_user_cards/files/6392738/Classes.txt)
Hallo Hamburger Jung,
wir nutzen deine Erweiterung um auf unserer Sportvereinsseite die Übungsleiter ordentlich präsentieren zu können.
Nach dem Upgrade auf Typo3 10 lief deine Erweiterung erst mal nicht. 

Folgender Code in der Datei fe_user_cards/Configuration/Extbase/Persistence/Classes.php lässt die Extensionen dann auch unter Typo3 10 laufen.

<?php
declare(strict_types = 1);

return [
    \HamburgerJungeJr\FeUserCards\Domain\Model\ExtendedFrontendUser::class => [
        'tableName' => 'fe_users',
        'properties' => [
            'feUserCardsPosition' => [
                'fieldName' => 'tx_fe_user_cards_position'
            ],
            'feUserCardsMobile' => [
                'fieldName' => 'tx_fe_user_cards_mobile'
            ],
            'feUserCardsSorting' => [
                'fieldName' => 'tx_fe_user_cards_sorting'
            ],
            'feUserCardsComments' => [
                'fieldName' => 'comments'
            ],			
        ],
    ],
];

Viele Grüße aus dem Pott

**Comment by HamburgerJungeJr** [comment]
Danke für den Hinweis, da ich noch kein Typo3 10 im Einsatz habe, konnte ich die Anpassung nicht testen.
Daher habe ich die Version noch nicht im TER veröffentlicht. 

Eine Vorabversion habe ich hier auf Github veröffentlicht: https://github.com/HamburgerJungeJr/fe_user_cards/releases/tag/1.4.1

**Comment by HamburgerJungeJr** [comment]
Eine aktuelle Version ist im TER
